fredmarpanama/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('', include('home.urls')),

]

home/urls.py
from django.urls import path
from . import views




app_name='home'
urlpatterns = [
    path('about/',views.AboutView.as_view(),name='about'),
]

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='products'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('categoria/<str:category>/',views.SearchCategory.as_view(),name='search_category'),
    path('contacto/',views.ContactView.as_view(),name='contact'),
    path('preguntar/',views.Preguntar,name='preguntar'),
    # path('about/',views.ProductSearchView.as_view(),name='product_search'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    is_active = models.BooleanField(default=True)
    meta_keywords = models.CharField("Meta Keywords",max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField("Meta Description", max_length=255, help_text='Content for description meta tag')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'categories'
        ordering = ['-created_at']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    image = models.ImageField(upload_to='photosProducts/')
    name = models.CharField(max_length=255, unique=True)
    brand = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.CharField(max_length=30)
    code = models.CharField(max_length=30)
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    stock = models.IntegerField()
    is_active = models.BooleanField()
    meta_keywords = models.CharField(max_length=255, help_text='Comma-delimited set of SEO keywords for meta tag')
    meta_description = models.CharField(max_length=255, help_text = 'Content for description meta tag')
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField(Category)

    class Meta:
        db_table = 'products'
        ordering = ['-created_at']


    def __str__(self):
        return f"{self.name}"


class Tag(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"

class Product_card(models.Model):
    image = models.ImageField(upload_to='Products_card/')
    name = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return f"{self.name}"

    def __repr__(self):
        return f"{self.name}"


class Contacto(models.Model):
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.CharField(max_length=1000)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}"

    def __repr__(self):
        return f"{self.name}"

# algunas configuraciones

class logo(models.Model):
    name = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='settings/logo')
    is_active = models.BooleanField(default=True)
    def __str__(self):
        return self.name



class carousel(models.Model):
    name = models.CharField(max_length=20)
    imageCarousel = models.ImageField(upload_to='settings/carousel')
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

products/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, CreateView
from .models import Product, Product_card, carousel, logo, Contacto
from .form import ContactForm


def save_pregunta_form(request, form):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string('preguntarForm.html', context, request=request)
    return JsonResponse(data)


def Preguntar(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
    else:
        form = ContactForm()
    return save_pregunta_form(request, form)



class PreguntarView(CreateView):
    form_class = ContactForm
    success_url = reverse_lazy('products:home')
    # data = dict()
    #
    # def form_valid(self, form):
    #     form.save()
    #     self.data['form_is_valid'] = True
    #     return JsonResponse(self.data)
    #
    # def form_invalid(self, form):
    #     self.data['form_is_valid'] = False
    #     return JsonResponse(self.data)

    def post(self, request, *args, **kwargs):
        # import ipdb; ipdb.set_trace()
        data = dict()
        get_form = self.get_form()
        form = get_form
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            # return JsonResponse(data)
        else:
            data['form_is_valid'] = False
        return JsonResponse(data)


    def get(self, request, *args, **kwargs):
        # import ipdb; ipdb.set_trace()
        data = dict()
        context = {'form': ContactForm}
        data['html_form'] = render_to_string('preguntarForm.html', context, request=request)
        return JsonResponse(data)





class ContactView(CreateView):
    form_class = ContactForm
    success_url = reverse_lazy('products:home')
    template_name = 'contacto.html'


class AjaxCategoryResponseMixin(object):
    def json_to_response(self):
        data = dict()
        category = self.kwargs.get('category', None)
        pCard = Product_card.objects.filter(categories__name__contains=category)
        data['products_card'] = render_to_string('products.html',{'object_list': pCard})
        return JsonResponse(data)


class HomeView(ListView):
    model = Product_card
    template_name = 'products.html'

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        imglogo = logo.objects.all()
        imgCarousel = carousel.objects.all()
        context.update({
            'imgCarousel':imgCarousel,
            'imglogo':imglogo,
        })
        return self.render_to_response(context)

class Home(TemplateView):
    template_name = 'base.html'



class SearchCategory(ListView):
    model = Product_card
    template_name = 'products.html'


    def get_queryset(self):
        category = self.kwargs.get('category', None)
        if category is not None:
            list = Product_card.objects.filter(categories__name__contains=category)
        else:
            list = Product_card.objects.all()[:10]
        return list

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()
        imglogo = logo.objects.all()
        imgCarousel = carousel.objects.all()
        context.update({
            'imgCarousel':imgCarousel,
            'imglogo':imglogo,
        })
        return self.render_to_response(context)







class ProductListView(ListView):
    model = Product
    template_name = 'store.html'

class ProductSearchView(ListView):
    model = Product
    template_name = 'store.html'

    def get_queryset(self):
        query = self.request.GET.get('q',None)
        if  query is not None:
            list = Product.objects.filter(name__contains=query)[:10]
        else:
            list = Product.objects.all()[:10]
        return list

products/templates/contacto.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 ">
                <form role="form" method="post">
                    <legend>Haznos una pregunta</legend>
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

products/templates/preguntarForm.html
{% load staticfiles %}
{% load bootstrap %}

<form role="form" method="post" action="{% url 'products:preguntar' %}" class="js-preguntar-form">
    {% csrf_token %}
    {{ form|bootstrap }}
    <div class="form-group" >
        <button type="submit" class="btn btn-primary">Enviar</button>
    </div>
</form>

products/templates/products.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap %}
{% block content %}
    {#  carousel de imagenes  #}
    {% include 'carousel.html' %}
    <section class="anuncio">
        <div class="container p-3">
            <h1 class="text-center titulo">Nuestros Productos<br></h1>
            <p class="text-center">Para mayor información o consulta por un modelo especifico&nbsp;<strong>Haz click en Preguntar</strong>.<br></p>
        </div>
    </section>
{#    productos #}
    <section>
        <div class="container">
            {# boton de categorias #}
            <div class="row justify-content-end mt-3">
                <div class="col-auto">
                    <div class="dropdown"><button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false" type="button">Categorias</button>
                        <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item opensans-4" role="presentation" href="{% url 'products:home' %}">Todas</a>
                            {% for category in categories %}
                                <a class="dropdown-item" role="presentation" href="{% url 'products:search_category' category %}">{{ category }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

                {#    tarjeta de producto   #}
                <div class="row">
                    {% for item in object_list %}
                        <div class="col-12 mt-3 col-md-6 col-lg-4">
                            <div class="tarjeta_producto border"><img src="{{ item.image.url }}" class="imagen_producto">
                                <div class="marca_producto pt-1 pb-1">
                                    {% for tag in item.tags.all %}
                                        <span>{{ tag }}</span>
                                    {% endfor %}
                                </div>
                                <div class="justify-content-end d-flex">
                                    <button type="button" class="btn btn-primary mr-1 mb-1 js-preguntar" data-toggle="modal" data-target="#preguntaModal" data-url="{% url 'products:preguntar' %}">Preguntar</button></div>
                                <div class="categorias border-top p-1">
                                    {% for category in item.categories.all %}
                                        <div class="tag d-inline-block roboto-9 f12">
                                            <a href="{% url 'products:search_category' category %}">{{ category }}</a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
        </div>
    </section>
        <!-- Modal -->
    <div class="modal fade" id="preguntaModal" tabindex="-1" role="dialog" aria-labelledby="preguntaModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="preguntaModalLabel">Haznos una pregunta</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ....
          </div>
        </div>
      </div>
    </div>


{% endblock %}