fredmarpanama/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
    path('', include('home.urls')),

]

home/urls.py
from django.urls import path
from . import views




app_name='home'
urlpatterns = [
    path('about/',views.AboutView.as_view(),name='about'),
]

products/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name='products'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('categoria/<str:category>/',views.SearchCategory.as_view(),name='search_category'),
    path('contacto/',views.ContactView.as_view(),name='contact'),
    path('preguntar/',views.Preguntar,name='preguntar'),
    # path('about/',views.ProductSearchView.as_view(),name='product_search'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fredmar Panama</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:300,400,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body style="background-repeat:no-repeat;background-size:contain;">
    <section class="menu-bar" style="width:100%;">
        <div style="background-color:#05E197;width:100%;height:5px;"></div>
    </section>
    <section>
        <div class="container">
            <nav class="navbar navbar-light navbar-expand-md d-block">
                <div class="container-fluid"><a class="navbar-brand" href="#" style="font-size:28px;"><strong>Fredmar Panama</strong></a><button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div
                        class="collapse navbar-collapse justify-content-end" id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'products:home' %}" >Inicio</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'home:about' %}" >Sobre Nosotros</a></li>
                            <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'products:contact'%}">Contactanos</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </section>

    {#  Contenido principal de la pagina  #}
    {% block content %}

    {% endblock %}



    {#pie de pagina#}
                <div class="footer-basic menus">
                    <footer>
                        <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
                        <ul class="list-inline">
                            <li class="list-inline-item"><a href="{% url 'products:home' %}">Inicio</a></li>
                            <li class="list-inline-item"><a href="{% url 'home:about' %}">Quienes Somos</a></li>
                            <li class="list-inline-item"><a href="{% url 'products:contact'%}">Contactanos</a></li>
                        </ul>
                        <p class="copyright">Fredmar Panama © 2018</p>
                    </footer>
                </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/carousel.html
{% load staticfiles %}

    <div class="carousel slide" data-ride="carousel" id="carousel-1">
        <div class="carousel-inner imagen-carousel" role="listbox">
            {% for item in imgCarousel %}
                {% if item.is_active %}
                    <div class="carousel-item"><img class="w-100 d-block" src="{{ item.imageCarousel.url }}" alt="Slide Image"></div>
                {% endif %}
            {% endfor %}
        </div>
        <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a></div>
        <ol class="carousel-indicators">
{#            <li data-target="#carousel-1" data-slide-to="0" class="active"></li>#}
{#            <li data-target="#carousel-1" data-slide-to="1"></li>#}
            {% for item in imgCarousel %}
                {% if item.is_active %}
                    <li data-target="#carousel-1" data-slide-to="1"></li>
                {% endif %}
            {% endfor %}
        </ol>
    </div>